#!/user/bin/env php
<?php

use App\Server; 
use App\Request;
use App\Response;

require 'vendor/autoload.php';

array_shift($argv);

if (empty($argv)) {
    $port = 80;
} else {
    $port = array_shift($argv);
}

$server = new server('127.0.0.1', $port);

$server->listen( function( Request $request ) 
{
	// print information that we recived the request
	echo $request->method() . ' ' . $request->uri() . "\n";
	
	// return a response containing the request information
	return new Response( '<pre>'.print_r( $request, true ).'</pre>' );
});